name: Publish Onsharp

on:
  push:
    branches:
      - master

jobs:
  build_project:
    name: Build DLL
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

  publish_nuget:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: build_project
    steps:
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: api/Onsharp/Onsharp.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

  publish_server:
    needs: build_project
    name: Publish to Update Server
    runs-on: ubuntu-latest
    steps:
    - uses: x/y
      with:
        PROJECT_FILE_PATH: api/Onsharp/Onsharp.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        ACCESS_TOKEN: ${{secrets.SERVER_ACCESS_TOKEN}}
        SERVER_URL: ${{secrets.SERVER_URL}}
